### ISSUE TITLE
Adding sccache to cache Rust builds

### ISSUE THREAD

**Issue by GZGavinZhao** [getsolus/solbuild#14]
# Rationale

`solbuild` already provides convenient caching with `ccache`, which greatly reduces package developers' time compiling C/C++ projects. However, `ccache` does not have the ability to cache Rust builds (at least not in a straight-forward way). Hence, it's quite annoying to completely rebuild a 400+-job Rust project when the only change is something very trivial, like a different install location. While it is true that Rust has incremental compilation, that is only for debug builds with `--incremental` flag turned on (default is on). Package developers do NOT benefit from this feature as they often, if not always, use `--release` builds.

# Solution

Use [`sccache`](https://github.com/mozilla/sccache) by Mozilla to cache Rust builds.

# Implementation

`sccache` will operate almost exactly like how `ccache` operates: mounting a cache directory. In `sccache`'s case, the location in the `chroot` environment would be `~/.cache/sccache`, and the location for the host machine can be `/var/lib/solbuild/sccache/**`. I have yet to figure out how `solbuild` redirect calls to `ccache`, so `sccache` will be different with `cache` in this area. For `sccache`, we can either export an environment variable (`RUSTC_WRAPPER="/usr/bin/sccache"`) or set the following in `~/.cargo/config.toml` in the `chroot` environment:
```toml
[build]
rustc-wrapper = "/path/to/sccache"
```
In this way, C/C++ builds will NOT be affected and only Rust compilations will get routed to `sccache`.

Final note: even though `sccache` can also cache C/C++ builds, this proposal is NOT about that. There's no intention of completely replacing `ccache` with `sccache`. `sccache` is supposed to assist `ccache` in areas that it doesn't work well, which, in this case, is Rust. Therefore, the logic of `solbuild` will not change at all.

I would love to implement and test this if accepted.

**Comment by joebonrichie** [comment]
Go for it :)

The existing flag `buildhelper = {none,ccache}` in `eopkg.conf` will need to used to control it.

I wasn't sure before looking but it looks like ccache gets enabled [here](https://github.com/getsolus/ypkg/blob/master/ypkg2/ypkgcontext.py#L240) in ypkg. Probably the easiest way to go about it to export `RUSTC_WRAPPER="/usr/bin/sccache"` somewhere sensible in ypkg if ccache is enabled and copy the ccache mount bind directory logic here within solbuild for sccache as you've suggested.

To ensure sccache is available in the chroot, the base solbuild image will need to be updated with sccache included. To work around this for local testing you can package sscache as system.devel locally or you can use extras.append in ypkg or see how iproute gets installed here in solbuild.

**Comment by GZGavinZhao** [comment]
Is `ccache` automatically enabled? If yes, I think `sccache` can follow suit. If packagers want to disable it, they can simply put `unset RUSTC_WRAPPER` in the `environments` section to override it.

Also, `sccache` is completely independent of `ccache`, so I don't think it's necessary to check if `ccache` is enabled.

**Comment by joebonrichie** [comment]
Yep ccache is enabled by default and so can sccache but we would need the global ccache setting to also control enablement of sccache as well. The solus build server has ccache disabled by default for example and it would just be easier if the existing ccache settings worked for sccache as well. Additionally, some people do not like to have ccache enabled to improve the initial build time which I imagine sscache would fall into the same vein. 

Following the existing logic in ypkg it would not be too difficult to control sscache with the default ccache setting, e.g.
```
if not self.spec.pkg_ccache:
    pass
if not self.build.ccache:
    pass
else:
    export RUSTC_WRAPPER="/usr/bin/sccache"
```

I'll also link to [init_default_exports](https://github.com/getsolus/ypkg/blob/master/ypkg2/scripts.py#L139) as that's where and how env variables gets exported to the build.

I know the interaction between ypkg and solbuild is a bit jank and ypkg is not very pretty but it is what it is :D.

**Comment by GZGavinZhao** [comment]
Understood! Thanks for the explanation!
