### ISSUE TITLE
sccache support breaks legacy builds

### ISSUE THREAD

**Issue by DataDrake** [getsolus/solbuild#19]
> mount: /var/cache/solbuild/unstable-x86_64/pisi/union/root/.cache/sccache: special device /var/lib/solbuild/sccache/legacy does not exist.

Basically, solbuild is trying to use an sccache device that doesn't exist. I haven't had a chance to dig into the root cause, but figured I'd report it. For now, I get around the issue by creating an empty directory for it to use after I delete my cache.

```
sudo mkdir /var/lib/solbuild/sccache/legacy
```

**Comment by GZGavinZhao** [comment]
It's probably my fault. I'll take a look at it and respond back here before the end of this week.
