### ISSUE TITLE
Drop git2go and switch to go-git for git sources functionality using ypkg3 reference code.

### ISSUE THREAD

**Issue by joebonrichie** [getsolus/solbuild#25]
The in-progress but currently stalled ypkg3 work has switched to using git-go for git cloning functionality.

There are four advantages to this:
- No longer having our tooling used to create pkgs depend on a versioned .so in libgit2 creating a chicken and egg situation
- Allow solbuild to be more portable but not depending on a specific .so._n_ version of libgit2
- Actual git submodule support
- Support for shallow cloning (generally desirable for our use-case)

The reference git support for ypkg3 using go-git can be found [here](https://dev.getsol.us/file/data/czd5oxl3qrbgbnch6qfh/PHID-FILE-2dv4visquiqwnzufyup2/git.go)

You'll notice it is very similarly architected to our current implementation: https://github.com/getsolus/solbuild/blob/master/builder/source/git.go

There are minimal out of file API calls anything that is missing to help understand the code can be provided if needed.

**Comment by silkeh** [comment]
Implemented in #39.
