### ISSUE TITLE
Support .config/solus/packager

### ISSUE THREAD

**Issue by chax** [getsolus/solbuild#6]
Implement support for reading packager info from `~/.config/solus/packager`

Do it same like here: https://dev.getsol.us/rCOMNac4493294bf109238822ec51307c2716caa094e9
and here: https://github.com/getsolus/ypkg/commit/902e8be1a7e6d49999ee9b971c1b22a21b4c2a80

This is where new path should be added:
https://github.com/getsolus/solbuild/blob/bbc91acc80cdcf29e5b6be7037be9ff8c8cba899/src/builder/userinfo.go#L125-L128

**Comment by JoshStrobl** [comment]
Resolved with 85035d86c52309e2e41cb087af1bc3e27915f33d as you noted on the Phab diff :slightly_smiling_face:
