### ISSUE TITLE
Write our own chroot support using syscall instead of calling `chroot` binary

### ISSUE THREAD

**Issue by joebonrichie** [getsolus/solbuild#66]
Instead of calling out the to the chroot binary write our own chroot support using the syscall.

This should be able to handle stdin and spawn a bash binary.

The main benefit of this is that we can immediately chroot into the $workdir directory instead of /home/user/.

See https://github.com/getsolus/solbuild/commit/f6588495a07e1841893e1acd51a58e08c57b4587 as a starting point, the difference being it'll have to spawn bash and handle stdin.

**Comment by ermo** [comment]
Fixed in #107
