### ISSUE TITLE
Put eopkg files in local repository if available

### ISSUE THREAD

**Issue by jepotter1-archive** [getsolus/solbuild#7]
It would make writing packages easier if there was an option to have solbuild put the  generated eopkg files into `/var/lib/solbuild/local` instead of the current directory.

This would help:
* Avoid accidentally checking eopkg files into git
* Make it easier to test packages using the local repository (skip having to copy the eopkg file over to `/var/lib/solbuild/local`)

Maybe implement a `-o` option to specify the output location?

**Comment by JoshStrobl** [comment]
> Avoid accidentally checking eopkg files into git

This is the wrong way of solving this. Use a global `.gitignore` to ignore the files.

> Make it easier to test packages using the local repository

This is something you can do already with something as simple as an alias, it's what I do.
