### ISSUE TITLE
Strip ANSI color escape sequences when not outputting to a real TTY

### ISSUE THREAD

**Issue by ermo** [getsolus/solbuild#76]
Logs currently look _atrocious_ in a web browser due to ANSI color escape sequences not being stripped when outputting to a file or piping.

It matters when reviewing build server logs in a browser and ought to be fixed once and for all.

**Comment by EbonJaeger** [comment]
When I output to a file and `cat` it, the colors appear fine in both Alacritty and gnome-terminal. How/where are you using this where it appears broken?

**Comment by ermo** [comment]
> When I output to a file and `cat` it, the colors appear fine in both Alacritty and gnome-terminal. How/where are you using this where it appears broken?

[solbuild logs](https://build.getsol.us) viewed in a web browser (which is incapable of parsing ANSI terminal escape codes as colors etc.)

I suspect this was silently fixed for 1.6.0 by @silkeh though.

**Comment by silkeh** [comment]
This was changed in #42 (included in 1.6.0): Solbuild now only enables the colored logger if the output is a TTY.
